### PR TITLE
add param to generic request

### PR DESCRIPTION
**Pull request by dpfaffenbauer**

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
will this get merged soon?

**Comment by dpfaffenbauer** [comment]
anyone?

**Comment by fjbender** [comment]
I would merge, but I dont have write access :/

**Comment by dpfaffenbauer** [comment]
@fjbender you know anyone who has?

**Comment by fjbender** [comment]
Maybe @pwnyprod ?

**Pull request closed without merging**
